on: 
 issues:
   types: [opened]
#on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    name: job1
    steps:
      - run: echo "step1"
      - run: echo "step2"
  job2:
    runs-on: ubuntu-latest
    name: job2
    needs: job1
    steps:
    - name: Hello
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'shello world!'
        color: 'yellow'